version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - my_network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysql -u root -p$MYSQL_ROOT_PASSWORD -e ''SELECT User FROM mysql.user WHERE User="$MYSQL_USER";''',
        ]
      timeout: 30s
      retries: 20
      interval: 1s
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy

    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
      - ssl_certs:/etc/nginx/ssl
    networks:
      - my_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      timeout: 30s
      retries: 20
      interval: 1s

volumes:
  db_data:
  wordpress_data:
  ssl_certs:

networks:
  my_network:
    driver: bridge
